CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE person(
	id UUID NOT NULL PRIMARY KEY, 
	name VARCHAR(50) NOT NULL, 
	date_of_birth DATE NOT NULL );

CREATE TABLE post (
	id UUID NOT NULL PRIMARY KEY,
	person_id UUID NOT NULL REFERENCES person(id),
	post_text VARCHAR(280)
);